<div class="controls">
    <?= $tabs ?>
</div>
<div class="content">
<?php if ($this->authz == false): ?>
    <p><?= $this->translate('You do not have the permission to execute commands.') ?></p>
<?php return; endif ?>
<p>
    <h2><?= $this->translate('Executed Command:') ?></h2>
</p>
    <pre><?= $this->command ?></pre>
<p>
    <h2><?= $this->translate('Output: ')?> </h2>
</p>
    <pre><?= $this->output ?></pre>
</div>
