<div class="controls">
    <?= $tabs ?>
</div>
<?php if ($this->auth==1): ?>
<div class="content">
<p>
    <h2><?= $this->translate('Executed Command:') ?></h2>
</p>
    <pre><?= $this->command ?></pre>
<p>
    <h2><?= $this->translate('Output: ')?> </h2>
</p>
    <pre><?= $this->output ?></pre>
</div>
<?php return; endif ?>

<?php if ($this->auth==0): ?>
<?= $this->authmsg ?>
<?php return; endif ?>
